# Generated by Django 5.2.4 on 2025-07-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingschedule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainingregistration',
            name='student',
        ),
        migrations.RemoveField(
            model_name='trainingregistration',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='TrainingRegistration',
        ),
        migrations.DeleteModel(
            name='TrainingSchedule',
        ),
    ]
