# Generated by Django 5.2.4 on 2025-07-27 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_student_trainingschedule_studentoptinout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingschedule',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='trainingschedule',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
