# Generated by Django 5.2.4 on 2025-07-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_rename_time_trainingschedule_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingschedule',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='trainingschedule',
            name='start_time',
        ),
    ]
